# Generated by Django 3.0.5 on 2020-04-25 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myfirm', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.CharField(max_length=50, unique=True)),
                ('dt_created', models.DateField(blank=True, default=None, null=True)),
                ('dt_delivery', models.DateField(blank=True, default=None, null=True)),
                ('pay_form_id', models.IntegerField(blank=True, default=None, null=True)),
                ('dt_pait_to', models.DateField(blank=True, default=None, null=True)),
                ('person_auth_name', models.TextField(blank=True, default=None, null=True)),
                ('price_sum_netto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_sum_brutto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_sum_brutto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dt_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirm.FirmData')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_number', models.IntegerField(blank=True, default=None, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoices')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Items')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.CharField(max_length=50, unique=True)),
                ('dt_created', models.DateField(blank=True, default=None, null=True)),
                ('dt_delivery', models.DateField(blank=True, default=None, null=True)),
                ('pay_form_id', models.IntegerField(blank=True, default=None, null=True)),
                ('dt_pait_to', models.DateField(blank=True, default=None, null=True)),
                ('name', models.TextField(blank=True, default=None, null=True)),
                ('items_number', models.IntegerField(blank=True, default=None, null=True)),
                ('price_sum_netto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_sum_brutto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('person_auth_name', models.TextField(blank=True, default=None, null=True)),
                ('paid_sum_brutto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dt_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirm.FirmData')),
                ('vat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Vats')),
            ],
        ),
    ]
