# Generated by Django 3.0.5 on 2020-04-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20200425_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='nr',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
