# Generated by Django 3.0.5 on 2020-04-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20200425_2321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoices0',
        ),
    ]
