# Generated by Django 3.0.5 on 2020-04-25 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField()),
                ('address_json', models.TextField(blank=True, default=None, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('nip', models.TextField(blank=True, default=None, null=True)),
                ('regon', models.TextField(blank=True, default=None, null=True)),
                ('pesel', models.TextField(blank=True, default=None, null=True)),
                ('bank_account', models.TextField(blank=True, default=None, null=True)),
                ('icon', models.TextField(blank=True, default=None, null=True)),
                ('dt_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
